Class {
	#name : 'MTAuxiliarTestClassForCompositeTestFilter',
	#superclass : 'TestCase',
	#category : 'MuTalk-TestResources',
	#package : 'MuTalk-TestResources'
}

{ #category : 'tests' }
MTAuxiliarTestClassForCompositeTestFilter >> testX1 [

	<pragma>
	
]

{ #category : 'tests' }
MTAuxiliarTestClassForCompositeTestFilter >> testX2 [

	
]

{ #category : 'tests' }
MTAuxiliarTestClassForCompositeTestFilter >> testX3 [

	<pragma>
	100 milliSeconds wait
]

{ #category : 'tests' }
MTAuxiliarTestClassForCompositeTestFilter >> testY1 [

	
]

{ #category : 'tests' }
MTAuxiliarTestClassForCompositeTestFilter >> testY2 [

	<pragma>
	
]
