Class {
	#name : 'MTAuxiliarClassForTestingStrategies',
	#superclass : 'Object',
	#category : 'MuTalk-TestResources',
	#package : 'MuTalk-TestResources'
}

{ #category : 'not defined category' }
MTAuxiliarClassForTestingStrategies >> aNotCoveredMethod [
	true ifTrue: [^2]
]

{ #category : 'not defined category' }
MTAuxiliarClassForTestingStrategies >> method1 [
	true ifTrue: [^1]
]

{ #category : 'not defined category' }
MTAuxiliarClassForTestingStrategies >> method2 [
	^2
]
