Class {
	#name : 'MTAuxiliarTestClassForBlockTestFilter',
	#superclass : 'TestCase',
	#category : 'MuTalk-TestResources',
	#package : 'MuTalk-TestResources'
}

{ #category : 'tests' }
MTAuxiliarTestClassForBlockTestFilter >> testX1 [

	self assert: true
]

{ #category : 'tests' }
MTAuxiliarTestClassForBlockTestFilter >> testX2 [

	self assert: true
]

{ #category : 'tests' }
MTAuxiliarTestClassForBlockTestFilter >> testY1 [

	self assert: true
]

{ #category : 'tests' }
MTAuxiliarTestClassForBlockTestFilter >> testY2 [

	self assert: true
]
