SystemOrganization addCategory: #'MuTalk-Model'!
SystemOrganization addCategory: 'MuTalk-Model-Logging'!
SystemOrganization addCategory: 'MuTalk-Model-Mutant evaluation results'!
SystemOrganization addCategory: 'MuTalk-Model-Mutant evaluation strategies'!
SystemOrganization addCategory: 'MuTalk-Model-Mutations generation strategies'!
SystemOrganization addCategory: 'MuTalk-Model-Operators'!
SystemOrganization addCategory: 'MuTalk-Model-Reporting'!
SystemOrganization addCategory: 'MuTalk-Model-Score'!
SystemOrganization addCategory: 'MuTalk-Model-TestCases selection strategies'!
