Class {
	#name : 'MTReplaceGreaterWithLessMutantOperator',
	#superclass : 'MTSelectorReplacementMutantOperator',
	#category : 'MuTalk-Model-Operators - Relational operation',
	#package : 'MuTalk-Model',
	#tag : 'Operators - Relational operation'
}

{ #category : 'accessing' }
MTReplaceGreaterWithLessMutantOperator >> newSelector [
	^#<
]

{ #category : 'accessing' }
MTReplaceGreaterWithLessMutantOperator >> oldSelector [
	^#>
]
