Class {
	#name : 'MTReplacePlusWithMinusMutantOperator',
	#superclass : 'MTSelectorReplacementMutantOperator',
	#category : 'MuTalk-Model-Operators - Arithmetic replacement',
	#package : 'MuTalk-Model',
	#tag : 'Operators - Arithmetic replacement'
}

{ #category : 'accessing' }
MTReplacePlusWithMinusMutantOperator >> newSelector [
	^#-
]

{ #category : 'accessing' }
MTReplacePlusWithMinusMutantOperator >> oldSelector [
	^#+
]
